countries = [
    "ARGENTINA",
    "AUSTRALIA",
    "AUSTRALIA NSW",
    "BANGLADESH",
    "BRAZIL",
    "BRAZIL RJ",
    "CHILE",
    "CHINA",
    "CHINA FUJIAN",
    "CHINA MACAU",
    "HONG KONG",
    "INDIA",
    "INDONESIA",
    "ISRAEL",
    "JAPAN",
    "KAZAKHSTAN",
    "KOR",
    "KOREA, REPUBLIC OF",
    "RUSSIAN FEDERATION",
    "SAUDI ARABIA",
    "COLOMBIA",
    "NEW ZEALAND",
    "PHILIPPINES",
    "SINGAPORE",
    "TAIWAN",
    "TAIWAN TAIPEI",
    "TAIWAN TAIWAN TAIPEI",
    "TURKEY",
]
jel_codes = [
    "C",
    "C0",
    "C1",
    "C2",
    "C3",
    "C4",
    "C5",
    "C6",
    "C7",
    "C8",
    "C9",
    "E",
    "E0",
    "E1",
    "E2",
    "E3",
    "E4",
    "E5",
    "E6",
    "E7",
    "F",
    "F0",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "G1",
    "G2",
    "G3",
    "G4",
    "G5",
    "I",
    "I0",
    "I1",
    "I2",
    "I3",
    "J",
    "J0",
    "J1",
    "J2",
    "J3",
    "J5",
    "J6",
    "M4",
    "N",
    "N0",
    "N4",
    "O",
    "O0",
    "O1",
    "O2",
    "O3",
    "O4",
    "P",
    "P0",
    "P1",
]
ejmcats = [
    "health",
    "macroeconomics",
    "development",
    "economic history",
    "labor",
    "insurance",
    "monetary",
    "growth",
    "behavioral economics",
    "statistics",
    "international trade",
    "public economics",
    "political economy",
    "international finance/macro",
    "experimental economics",
    "microeconomic theory",
    "management",
    "theory",
    "decision sciences",
    "econometrics",
    "accounting",
    "organizational behavior",
    "computational economics",
    "education",
]
